name: inventory
description: A new Flutter project.

publish_to: "none"

version: 1.0.26+26

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  bloc: ^8.0.3
  calendar_date_picker2: ^0.5.2
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^4.0.6
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_barcode_scanner: ^2.0.0
  flutter_bloc: ^8.0.1
  flutter_svg: ^1.1.6
  get_it: ^7.6.0
  google_fonts: ^6.0.0
  intl: ^0.18.1
  introduction_screen: ^3.0.2
  responsive_framework: ^0.1.4
  scroll_to_index: ^3.0.1
  shared_preferences: ^2.0.15
  smooth_highlight: ^0.1.1
  time_remaining: ^2.0.0+1

dependency_overrides:
  intl: ^0.18.1

dev_dependencies:
  bloc_test: ^9.0.3
  build_runner: null
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  hive_generator: null
  mocktail: ^0.3.0

flutter_icons:
  image_path: "assets/icon/launcher/icon_so.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon/launcher/adaptive_logo.png"
  android: true
  # ios: true

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - pubspec.yaml
    - assets/icon/home/
    - assets/icon/launcher/
    - assets/icon/splash/
    - assets/images/onboarding/
    - assets/images/sign_in/
    - assets/images/home/
    - assets/icon/operation/
  #   - images/a_dot_ham.jpeg
